import { useState, type CSSProperties } from "react";
import { ArrowRight, Check, Circle, Layers2, LockKeyhole, Monitor, MousePointer2, Sparkles } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { readableInk, type PaletteColors } from "@/lib/colorlab";
export default function LivePreview({ colors }: { colors: PaletteColors }) {
  const [favorite, setFavorite] = useState(false), [message, setMessage] = useState("");
  const theme = { "--preview-bg": colors[0], "--preview-surface": colors[1], "--preview-accent": colors[2], "--preview-primary": colors[3], "--preview-text": colors[4], "--preview-on-primary": readableInk(colors[3]), "--preview-on-accent": readableInk(colors[2]) } as CSSProperties;
  return <section className="preview-panel" aria-labelledby="preview-heading">
    <div className="panel-heading"><h2 id="preview-heading"><Monitor size={19} /> Vista en vivo</h2><span className="live-tag"><span /> Tu paleta en acción</span></div>
    <div className="browser-frame"><div className="browser-chrome"><div className="browser-dots" aria-hidden="true"><i /><i /><i /></div><span><LockKeyhole size={11} /> forma.studio</span><span className="preview-label">VISTA DE MUESTRA</span></div><div className="demo-site" style={theme}>
      <Tabs defaultValue="website" className="demo-tabs"><div className="demo-header"><span className="demo-logo"><Layers2 size={21} strokeWidth={2.4} />forma<span>®</span></span><TabsList className="demo-nav" aria-label="Vistas de la interfaz de muestra"><TabsTrigger value="website">Estudio</TabsTrigger><TabsTrigger value="components">Componentes</TabsTrigger></TabsList><span className="demo-header-end">Diseño con intención <span>↗</span></span></div>
      <TabsContent value="website" className="demo-content"><div className="demo-hero"><div className="demo-hero-copy"><span className="demo-eyebrow"><span /> UN POCO DE COLOR. MUCHAS IDEAS.</span><h3>Las buenas ideas<br />tienen <em>su color.</em></h3><p>Un espacio para crear, experimentar<br className="desktop-break" /> y dar forma a lo que imaginas.</p><button className="demo-primary-button" onClick={() => { document.getElementById("demo-form")?.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth", block: "nearest" }); document.getElementById("demo-name")?.focus({ preventScroll: true }); }}>Dale forma <ArrowRight size={16} /></button></div><div className="type-composition" aria-hidden="true"><span className="type-top">CREA SIN LÍMITES</span><span className="type-aa">Aa<span>✳</span></span><div className="type-bottom"><span>Pequeñas ideas.<br />Grandes posibilidades.</span><span className="type-mark">f.</span></div></div></div>
      <div className="demo-cards"><article className="demo-card"><span className="demo-card-icon"><Sparkles size={19} /></span><div><h4>Un nuevo comienzo</h4><p>Todo empieza con una idea.</p></div><button className={`demo-save ${favorite ? "active" : ""}`} onClick={() => setFavorite(!favorite)} aria-pressed={favorite} aria-label={favorite ? "Quitar selección de la tarjeta de muestra" : "Seleccionar tarjeta de muestra"}>{favorite ? <Check size={18} /> : <ArrowRight size={18} />}</button></article><form className="demo-form" id="demo-form" onSubmit={(event) => { event.preventDefault(); const values = new FormData(event.currentTarget); const name = String(values.get("name") || "").trim(); if (name) setMessage(`¡Hola, ${name}! Tu idea empieza aquí.`); }}><label htmlFor="demo-name">¿Cómo llamamos a tu próxima idea?</label><div><input id="demo-name" name="name" placeholder="Escribe un nombre…" required maxLength={40} autoComplete="off" /><button aria-label="Probar formulario de muestra"><ArrowRight size={18} /></button></div>{message && <p role="status" className="demo-form-message">{message}</p>}</form></div></TabsContent>
      <TabsContent value="components" className="demo-component-content"><div className="component-intro"><span className="demo-eyebrow">LOS DETALLES TAMBIÉN CUENTAN</span><h3>Una paleta, muchas formas.</h3></div><div className="component-examples"><div><span className="component-label">BOTONES</span><button className="demo-primary-button" onClick={() => setMessage("Así se ve el botón principal al pulsarlo.")}>Principal <ArrowRight size={16} /></button><button className="demo-secondary-button" onClick={() => setMessage("Así se ve el botón secundario al pulsarlo.")}>Secundario</button></div><div><span className="component-label">ETIQUETAS</span><span className="demo-pill">En proceso</span><span className="demo-pill accent-pill"><Check size={14} /> Completado</span></div><div className="component-card"><Circle size={22} /><h4>Espacio para tus ideas</h4><p>Fondos, bordes y texto que comparten el mismo lenguaje.</p></div><div className="component-surface"><span className="component-label">TIPOGRAFÍA</span><strong>Aa Bb Cc</strong><p>El comienzo de algo bueno.</p></div></div><p className="component-message" role="status">{message || "Pulsa los botones para probar sus estados."}</p></TabsContent></Tabs>
    </div></div><p className="preview-caption"><MousePointer2 size={14} /> Prueba los botones y el formulario. Todos los colores vienen de tu paleta.</p>
  </section>;
}
